application:
  subdomain: neoapi
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://neo-api:3000/
services:
  neo-api:
    # pengzhile/new-api:v1.5.10
    # upstream: docker.io/pengzhile/new-api:2026.3.21
    image: registry.lazycat.cloud/czyt/pengzhile/new-api:5d8328a4cdba0f9e
    environment:
      - TZ=Asia/Shanghai
      - ALL_PROXY=
      - SESSION_SECRET={{ stable_secret "neo@session" }}
      - REDIS_CONN_STRING=redis://redis
    binds:
      - /lzcapp/var/data:/data

    depends_on:
      - redis

  redis:
    image: registry.lazycat.cloud/czyt/library/redis:084c4dbb68f32013
