name: Neo API
package: cloud.lazycat.app.neoapi
version: 1.5.4
min_os_version: 1.3.8
description: new-api LINUX DO 魔改版
homepage: https://hub.docker.com/r/pengzhile/new-api
author: pengzhile
application:
    subdomain: neoapi
    background_task: true
    public_path:
        - /
    upstreams:
        - location: /
          backend: http://neo-api:3000/
services:
    neo-api:
        container_name: neo-api
        # docker.1ms.run/pengzhile/new-api:v1.5.4
        image: registry.lazycat.cloud/czyt/pengzhile/new-api:d63fcad4234dcbd4
        environment:
            - TZ=Asia/Shanghai
            - TIKTOKEN_CACHE_DIR=/data/cache
        command: --log-dir /app/logs
        binds:
            - /lzcapp/var/data:/data
            - /lzcapp/var/logs:/app/logs
            - /lzcapp/var/cache:/data/cache

unsupported_platforms:
    - ios
    - android
    - tvos
